apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
        - name: celery-beat
          image: vishnuvardhandommeti/bank:v1
          command: ["celery", "-A", "BankingSystem", "beat", "--loglevel=info"]
          env:
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: CELERY_BROKER_URL
              value: "redis://redis-service:6379/0"
            - name: CELERY_RESULT_BACKEND
              value: "redis://redis-service:6379/0" 