apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'django-app'
        metrics_path: "/metrics"
        static_configs:
          - targets: ['django-service.default.svc.cluster.local:8000']
            labels:
              service: "django-app"

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
            labels:
              service: "prometheus"

      - job_name: 'redis'
        static_configs:
          - targets: ['redis-exporter.monitoring.svc.cluster.local:9121']
            labels:
              service: "redis"
